# Site settings
title: Arete EdTech
email: sandy@areteedtech.org
description: > # this means to ignore newlines until "baseurl:"
  Our mission: To promote computer science education opportunities in St. Louis area schools; with an emphasis on reaching low-income and female students.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://areteedtech.org" # the base hostname & protocol for your site
twitter_username: AreteEdTech
github_username: Arete-EdTech

# Build settings
markdown: kramdown
